import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, 'data')
LOG_DIR = os.path.join(BASE_DIR, 'logs')

CAMERA_INDEX = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FPS_TARGET = 30

HAND_DETECTION_CONFIDENCE = 0.5
HAND_TRACKING_CONFIDENCE = 0.5
MAX_NUM_HANDS = 2

FINGER_TIP_IDS = [4, 8, 12, 16, 20]
FINGER_NAMES = ['Thumb', 'Index', 'Middle', 'Ring', 'Pinky']

SHOW_HAND_LANDMARKS = True
SHOW_HAND_CONNECTIONS = True
SHOW_FINGER_COUNT = True
SHOW_HAND_LABEL = True
FONT_SCALE = 1.0
FONT_THICKNESS = 2

ENABLE_TTS = False
ENABLE_LOGGING = True
ENABLE_SCREENSHOTS = True

LOG_FILE = os.path.join(LOG_DIR, 'hand_detections.csv')

COLOR_BLUE = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_RED = (0, 0, 255)
COLOR_YELLOW = (0, 255, 255)
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_CYAN = (255, 255, 0)
COLOR_MAGENTA = (255, 0, 255)

LEFT_HAND_COLOR = (0, 255, 0)
RIGHT_HAND_COLOR = (255, 0, 0)
